### ISSUE TITLE
[1.21.1] Can't respawn after dying

### ISSUE THREAD

**Issue by WhitePhant0m** [Jarva/Ars-Additions#5]
[Error given by respawn attempt](https://mclo.gs/lryQPPu#L4788)

Pack: [Craftoria v0.9.0](https://www.curseforge.com/minecraft/modpacks/craftoria/files/5661904)

Steps taken:
Fresh world, died by using `/damage @s 20`, can't respawn, same with `/kill @s`, and by dying any other way.
Removing Ars-Additions allows respawning again

[Manually triggered crash for modlist](https://mclo.gs/HVpw6h8)

**Comment by Jarva** [comment]
This is now fixed in 21.0.0-alpha2

## Links
[Modrinth](<https://modrinth.com/mod/ars-additions/version/21.0.0-alpha2>)
[CurseForge](<https://legacy.curseforge.com/minecraft/mc-mods/ars-additions/files/5663351>)
[GitHub](<https://github.com/Jarva/Ars-Additions/releases/tag/21.0.0-alpha2>)
[Discord](<https://discord.com/invite/kxUxmhQguE>)
